# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --ignore-engines --frozen-lockfile
      - run:
          name: Verify Cypress
          command: yarn run cypress verify
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Start server and run Cypress
          command: yarn test
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos